[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =

build_flags =
    -D UA_ARCHITECTURE_FREERTOSLWIP
    -D UA_ENABLE_AMALGAMATION
    -Wno-write-strings
    -Wno-discarded-qualifiers
